### ISSUE TITLE
Mismatch between starting tritet text and summary table

### ISSUE THREAD

**Issue by scouten-adobe** [WebOfTrust/ietf-cesr#43]
The text in the following paragraph …

https://github.com/WebOfTrust/ietf-cesr/blob/50b55f29257bc610209100a650cb03857563f159/draft-ssmith-cesr.md?plain=1#L520

> Otherwise, if a stream starts with 0b100 then is JSON, with 0b101 then its CBOR, and with either 0b011, and 0b110 then its MGPK.[¶](file:///Users/scouten/Projects/ietf-cesr/draft-ssmith-cesr.html#section-3.6.1-5)

… appears to disagree with the summary table immediately following …

https://github.com/WebOfTrust/ietf-cesr/blob/50b55f29257bc610209100a650cb03857563f159/draft-ssmith-cesr.md?plain=1#L525-L534

… which shows JSON as starting with the tritet 0b011.

Please consider reconciling these or adding an explanation for the discrepancy.

**Comment by scouten-adobe** [comment]
Also, proofreading nit: The "its" quoted above in line 520 should be "it's" (as a contraction for "it is").

**Comment by SmithSamuelM** [comment]
Fixed with #46
