### ISSUE TITLE
Possible copy/paste error in Base64

### ISSUE THREAD

**Issue by scouten-adobe** [WebOfTrust/ietf-cesr#44]
The last sentence of [line 518](https://github.com/WebOfTrust/ietf-cesr/blob/50b55f29257bc610209100a650cb03857563f159/draft-ssmith-cesr.md?plain=1#L518) says …

> To elaborate, Base64 uses _ in position 62 or 0x3E (hex) and uses _ in position 63 or 0x3F (hex) both of which have starting tritet of 0b111

I think it should say hyphen in position 62 and underscore in position 63, based on my reading of [RFC 4648 section 5](https://datatracker.ietf.org/doc/html/rfc4648#section-5).

**Comment by SmithSamuelM** [comment]
fixed with #46
